// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetQuestions():Promise<Array<model.Question>>;

export function Greet(arg1:string):Promise<string>;

export function LoadQuestions():Promise<Array<model.Question>>;

export function Login(arg1:string):Promise<model.LoginResponse>;

export function SetQuestions(arg1:Array<model.Question>):Promise<void>;
