// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQuestions() {
  return window['go']['main']['App']['GetQuestions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadQuestions() {
  return window['go']['main']['App']['LoadQuestions']();
}

export function SetQuestions(arg1) {
  return window['go']['main']['App']['SetQuestions'](arg1);
}
